[project]
name = "Autoantibody-quantification"
version = "0.1.0"
description = "measures Abb intensity"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
"matplotlib",
"numpy",
"tifffile",
"scipy"
]
